const express = require("express");
const router = express.Router();
const methodDeliAPI = require("../controllers/methodDeliControllers");
const vnpayAPI = require("../controllers/vnpayControllers");
router.post("/create_method", methodDeliAPI.createMethod);
router.put("/:id", methodDeliAPI.updateMethod);
router.get("/all_methods", methodDeliAPI.getAllMethods);
router.get("/all_methods/admin", methodDeliAPI.getAllMethodsAdmin);
router.delete("/:id", methodDeliAPI.deleteShippingPartner);
router.patch("/update-status", methodDeliAPI.updateStatus);
router.post("/vn_pay", vnpayAPI.createPaymentUrl);
router.post("/create_refund", vnpayAPI.createRefundRequest);
router.get("/vnpay_ipn", vnpayAPI.vnPayIPN);
module.exports = router;
